targets:
  $default:
    builders:
      bloc_gen|bloc_gen:
        enabled: true
        generate_for:
          - example/lib/**.dart
          - lib/**.dart
          - test/**.dart

builders:
  bloc_gen:
    import: "package:bloc_gen/builder.dart"
    builder_factories: ["eventGenerator"]
    build_extensions: {".dart": [".bloc_gen.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]