name: fbloc_event_gen
description: Generates event classes from factory constructors
version: 1.0.2
repository: https://github.com/naveen-as-a-geek-wolf/bloc_gen
issue_tracker: https://github.com/naveen-as-a-geek-wolf/bloc_gen/issues
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ^6.5.0
  build: ^2.4.1
  equatable: ^2.0.7
  source_gen: ^1.3.2

dev_dependencies:
  build_runner: ^2.4.6
  build_test: ^2.2.0
  
