name: event_generator
description: A package to generate event subclasses using build_runner
version: 1.0.0
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  build: ^2.4.1
  source_gen: ^1.3.2
  analyzer: ^5.13.0  # Using an older version that's compatible

dev_dependencies:
  build_runner: ^2.4.6
  build_test: ^2.2.0
  test: ^1.24.0
  dart_style: ^2.3.1  # Explicitly defining